### ISSUE TITLE
Page not loading. Need settings help

### ISSUE THREAD

**Issue by BiglifeMatt** [rotdrop/nextcloud-roundcube#14]
I cannot get the page to load although it appears to be trying.  I get a Missing Page icon in Chrome but Firefox makes it look like it isn't a trusted source or doesn't have permission.  I'm trying to follow the configuration but am not sure how my scenario fits in so I will describe my setup.

I'm using an OpenLDAP server to authenticate both my email (iRedMail) and my Nextcloud accounts.  The OpenLDAP and iRedMail and Roundcube are all installed on the same virtual server.  The Nextcloud is on another virtual server.  Both servers are a part of the same DNS domain.  Any guidance on steps that may be more specific to this scenario would be welcome.

**Comment by HLFH** [comment]
A screenshot would help.

**Comment by BiglifeMatt** [comment]
Sorry, this was quite a while back and was resolved (cannot recall how now) so I can close this.
