### ISSUE TITLE
Support Nextcloud 26

### ISSUE THREAD

**Issue by marcotrevisan** [rotdrop/nextcloud-roundcube#15]
Hi all, 

  the current release does not explicitly support NC 26.
Are there any known issues preventing it? 
We are holding back the upgrade of Nextcloud from 25 to 26.

Thanks and regards,
  Marco

**Comment by Luncheon3462** [comment]
Hi. Appreciate the developer's efforts. The nextcloud mail app is quite slow and haven't had much luck with snappymail. With nextcloud moving to 27, I wanted to ask about plans for updating this app to be compatible with NC26 and NC27. I don't code, but can make a donation/set a bounty to help with the dev's efforts. Just need to know where/how.

I see on the nextcloud site that someone had success changing the info.xml file and getting the app to work in NC26.   I tried the same (changing the lines for PHP and NC dependencies), but didn't have the same luck.

**Comment by HLFH** [comment]
NC 26 & NC 27 are supported on the master branch.

@rotdrop should merge this PR: https://github.com/rotdrop/nextcloud-roundcube/pull/18, and submit the new release 1.0.3.

**Comment by marcotrevisan** [comment]
I think the most important thing is keeping it up to date with the current versions, ...nice if support for earlier ones is kept for as long as possible if it doesn't hurt.

**Comment by rotdrop** [comment]
So, the current pre-release actually does not work with NC 26. I have compiled the release on v28 and verified that it also works with v27, however, if I just untar the release tar-ball in a fresh NC 26 install it does not work. Seems  to be related to a javascript incompatibility.

**Comment by rotdrop** [comment]
"Unfortunately" I was wrong: it just works with NC26. I just ran in to some strange configuration edge case. YMMV, but chances are that it just works. Of course, the look and feel of the settings UI is that of NC28.

It helps that the PHP dependencies of this package are close to non-existing (talking about composer).

**Comment by rotdrop** [comment]
Closing in favour of #23.
