### ISSUE TITLE
Not working on Nextcloud 27

### ISSUE THREAD

**Issue by Sofahamster** [rotdrop/nextcloud-roundcube#17]
It appears that some things have changed with newer versions of Nextcloud, that break this addon.

If you try to open roundcube with this plugin, you get an almost empty nextcloud page with a loading progress indicator (that looks kinda out of place, style-wise), but nothing happens.

The web console shows the following error message:

Uncaught TypeError: this.frameElement is undefined
    loadTimerHandler App.vue:121
    setTimeout handler*mounted App.vue:90
    VueJS 13
    <anonymous> app.js:34
    <anonymous> app.js:36
    <anonymous> app.js:36

**Comment by HLFH** [comment]
Same issue...

**Comment by HLFH** [comment]
It works if you configure SMTP/IMAP selection in your Roundcube config file.

```
$config['imap_host'] = array(
    'ssl://imap.example.com:993' => 'example.com',
    'ssl://imap.example2.com:993' => 'example2.com'
);
$config['smtp_host'] = array(
    'ssl://smtp.example.com:465' => 'example.com',
    'ssl://smtp.example2.com:465' => 'example.com'
);
```

**Comment by HLFH** [comment]
Issue can be closed thanks to this PR: https://github.com/rotdrop/nextcloud-roundcube/pull/18

**Comment by ezeik** [comment]
Hi, NC27(Inside docker) + IRedMail (with RoundCube 1.6.1). They was installed on different domains and different Web-Server. How to make them work with use NginxProxyManager

**Comment by rotdrop** [comment]
> Hi, NC27(Inside docker) + IRedMail (with RoundCube 1.6.1). They was installed on different domains and different Web-Server. How to make them work with use NginxProxyManager

Late reply. I suppose that you already had a look at the changes by @HLFH who added a section to the README.md file.

**Comment by rotdrop** [comment]
If I understand things correctly this issue more or less talks about configuration issues on the Roundcube side of things. Please correct me if I am wrong. I am keeping this issue open until v1.1.0 is released (probably on Wednesday this week).
