### ISSUE TITLE
Nextcloud 28 & PHP 8.2 compatibility

### ISSUE THREAD

**Issue by nextgen-networks** [rotdrop/nextcloud-roundcube#20]
Roundcube can't be activated on Nextcloud 28 - would be great to have that enabled for NC 28.
... as well as on a PHP 8.2 or PHP 8.3 enabled server.

Thanks!

**Comment by melroy89** [comment]
Developers.. Plz????

**Comment by rotdrop** [comment]
There is now a pre-release v1.1.0-rc1 which addresses among other things compatibility with NC 28. Please give it a try if you can.

**Comment by rotdrop** [comment]
Closing in favour of #23.
