### ISSUE TITLE
Release for Nextcloud 28

### ISSUE THREAD

**Issue by as400l** [rotdrop/nextcloud-roundcube#21]
Would it be possible to add new release for Nextcloud 28 ?

**Comment by jdaviescoates** [comment]
Yeah, it'd be great if this app could be updated to be compatible with Nextcloud 28!

**Comment by nmchm** [comment]
Yes guys! Please bring it to Nextcloud 28.

Thanks for the effort.

**Comment by rotdrop** [comment]
Closing in favour of #23.
