### ISSUE TITLE
Release v1.1.0

### ISSUE THREAD

**Issue by rotdrop** [rotdrop/nextcloud-roundcube#23]
The forthcoming release v1.1.0 should solve the issues #21, #20 and #15.

IMHO the remaining issue #17 is about configuration problems not with **this** app, but with the Roundcube installation one tries to integrate. But maybe I misunderstood things.

I am now closing #15, #20 and #21 in favour of this issue. If you have problems with the pre-releases or the final release once it is there please feel free to comment here or open a new issue. Kind thanks!

For the time-line: I will wait until the translation teams had their time to add new translations, the final v1.1.0 is then to be expected, say, on Wednesday.

Best

Claus

**Comment by as400l** [comment]
Many thx @rotdrop.

Just installed rc3 on 28.0.3 from tarball. Works beautifully with RC 1.6.5.

**Comment by rotdrop** [comment]
> Many thx @rotdrop.
> 
> Just installed rc3 on 28.0.3 from tarball. Works beautifully with RC 1.6.5.

Thank you! In case that you have also installed the CardDAV plugin  I would be interested in feedback whether the new auto configuration feature works. To be honest, this is the only new feature introduced with v1.1.0 (supporting new NC version is laborious but not so exciting ...)

**Comment by as400l** [comment]
I have this plugin installed. And I'm using it for a long time. So all of my adressbooks were already configured.

But I think I have one thing that wasn't there if I remember correctly. Would this auto configuration feature create an addressbook called "Accounts" ?

With the below URL:

https://some.hostname/remote.php/dav/addressbooks/users/username/z-server-generated--system/

**Comment by rotdrop** [comment]
Well, as far as I understand it the latest version (and perhaps also previous versions) of the Roundcube CardDAV plugin are able to detect the complete collection of available address books. So I believe that those z-... app generated address books are included.

However, it I understood it  correctly this new "pre configuration" feature of the CardDAV plugin is to provide sort of "provisioning" for the address books. And this is the point where the Nextcloud app joins in: if you point a pre-configured address book configuration to the Nextcloud address books, then the Nextcloud RC integration app (oops, **this** app) installes the correct username and an app-password into Roundcube such that those address books are automatically accessible. In my setup I am running a Nextcloud instance for the executive board of an orchestra; in this multi-user setup is very convenient to have this integration without having to explain the details to the users (they would not listen anyway, either things work out of the box or things will not be used at all ;) ).

**Comment by nextgen-networks** [comment]
> The forthcoming release v1.1.0 should solve the issues #21, #20 and #15.
> 
...
> 
> Best
> 
> Claus

Hello @rotdrop (and dear users of this module),

thanks for all your effort you took into that release!

Sadly my configurations are not working in both web-server-setup modes ("proxy_pass" as well as via "alias").
Im using Plesk with nginx only and PHP 8.2 FPM.
NC as well as Roundcube are located on the same server. NC is on a main domain. Roundcube is available via subdomain or path.

In "alias" Config i had to comment out the "fastcgi_pass php-handler;" part as the Plesk nginx configuration did not allowed that parameter (suppose it is already set in global config).

In both configuration cases I received a error message and download option as you can see in screenshot.
![image](https://github.com/rotdrop/nextcloud-roundcube/assets/21206978/26efde8c-701b-45e6-bb67-e3db9a3881d7)

The regular login to Roundcube via subdomain von NC is working fine.

Any idea/hint (besides of the Roundcube path option) where to look at?
... or experiences with a similar issue and some hints for a solution? :-)

Again: Many thanks for the continued development as well as community support!

**Comment by rotdrop** [comment]
I actually map my Roudcube instance via an alias directive into the same domain as my NC instance, like this:
```
Alias /roundcube /var/www/localhost/htdocs/roundcubemail
<Directory /var/www/localhost/htdocs/roundcubemail>
        AllowOverride All
        Require all granted
</Directory>
```
This is actually my test-setup @home. So NC is available via `https://foobar.example.com` and Roudcube below `https://foobar.example.com/roundcube`. I am  not so sure that a subdomain approach will work. This download offer looks strange. Perhaps you could use the developer tools of your web-browser and search for the iframe element which should  hold the RC content? This download offer looks strange.

**Comment by rotdrop** [comment]
Do you have a chance to use the developer console of the web-browser in order to inspect what is actually inside the Roundcube iframe and what reposonses are received by the web browser?

**Comment by nextgen-networks** [comment]
> Alias /roundcube /var/www/localhost/htdocs/roundcubemail
> <Directory /var/www/localhost/htdocs/roundcubemail>
>         AllowOverride All
>         Require all granted
> </Directory>

The mentioned Alias looks like a Apache .htaccess setting right?

Have to skip tests today. I'll try to figure out logs from dev console tomorrow and share results here.

**Comment by nextgen-networks** [comment]
> > Alias /roundcube /var/www/localhost/htdocs/roundcubemail
> > <Directory /var/www/localhost/htdocs/roundcubemail>
> > AllowOverride All
> > Require all granted
> 
> The mentioned Alias looks like a Apache .htaccess setting right?
> 
> Have to skip tests today. I'll try to figure out logs from dev console tomorrow and share results here.

Ok got a soloution/workaround:
Needed to comment out some recomendations (https://docs.nextcloud.com/server/latest/admin_manual/installation/nginx.html) for NGINX:

1. the serve static files part:
```
# Serve static files
    location ~ \.(?:css|js|mjs|svg|gif|png|jpg|ico|wasm|tflite|map|ogg|flac)$ { ...
```

2. as well as "woff2" part
```
 location ~ \.woff2?$ {
        try_files $uri /index.php$request_uri;
```

Right after that change everything worked again ...

Thanks @rotdrop & @HLFH for your ongiog work on that implementation

**Comment by rotdrop** [comment]
Well as the release is done I am closing this issue now. Please feel free to open new issues.
