### ISSUE TITLE
Config error after intalling

### ISSUE THREAD

**Issue by dimatr-iva** [rotdrop/nextcloud-roundcube#24]
Hello.

Help plz with config error after app install.

Debian, Nextcloud 28(php 8.1.27), roundcube 1.6.1(php 8.1.27) - all works fine

Try to enter roundcube directory in config page after app installed (1.1.0):
https://cloud.site.com/rcube/

In browser URL https://cloud.site.com/rcube/ also works well

But in nextcloud.log:
Traits cannot have constants at /var/www/www-root/data/www/site.com/apps/mail_roundcube/lib/Toolkit/Traits/ResponseTrait.php#45

What i'm doing wrong?
Thanks a lot for your answers!

**Comment by rotdrop** [comment]
This should be fixed now by 5d7773c and the forthcoming release v1.1.1.

**Comment by dimatr-iva** [comment]
Thanks!!!!
