### ISSUE TITLE
Error 500 - dependency missing?

### ISSUE THREAD

**Issue by nextgen-networks** [rotdrop/nextcloud-roundcube#3]
Hey rotdrop,

thanks creating this repo and providing a fresh version for testing the RoundCube 1.6 compatibility.

I tried to use your "master" master branch with my NC25/RC1.6 setup and got an error as follows:
2612210#0: *6515 FastCGI sent in stderr: "PHP message: PHP Fatal error: Trait "OCA\RotDrop\Toolkit\Traits\AppNameTrait" not found in /var/www/vhosts/nameOfInstance/nameOfNCDomain/apps/roundcube/lib/AppInfo/Application.php on line 59" while reading response header from upstream

That leads to an server error 500.

Is there any additional toolkit that needs to be installed but is not bundled in current repo?

**Comment by rotdrop** [comment]
Hi, did you try to compile the thing? The assets are not stored in the git repository.

**Comment by rotdrop** [comment]
Oops. Missing include, wait a bit ...

**Comment by rotdrop** [comment]
Hi there,

you can try to extract the "release" tar-ball (there is only one under https://github.com/rotdrop/nextcloud-roundcube/releases/tag/v1.0.0-rc0). 

For the compilation: you need composer and npm and then could run "make" in the app's directory. That "rc0" release just contains the "compiled" sources and principle should be such that it could be uploaded to the app store. Just I did no testing whatsoever with it.

**Comment by rotdrop** [comment]
FYI, just update the assets now.

**Comment by nextgen-networks** [comment]
Hey Rotdrop,

problem is solved with the latest asset additions made yesterday - thank you very much!

(Now facing some parsing problems within RC - but this is a separate topic ;-) )
